[tool.poetry]
name = "skybank"
version = "0.1.0"
description = ""
authors = ["Максим Морозов <mar0z0v@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
